sudo: false
language: node_js
node_js:
#LTS
  - "10"
  - "16"
  - "node"
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm test
after_success:
  - npm run report-coverage